#!env ruby

sd = File.dirname($0)
require sd+'/lib/Netest.rb'
require sd+'/lib/NetestTarget.rb'

def print_usage
	puts "usage: netest config_file"
end
	
	if ARGV.size < 1
		print_usage
		exit 1
	end
	
	scenario_file = ARGV[0]
	unless File.exists?(scenario_file)
		puts "scenario file not found: #{scenario_file}"
	end
	
	scenario = eval File.read(scenario_file)
	
	$semaphore = Mutex.new
	netest = Netest.new
	netest.load_scenario scenario
	netest.do_test
	
