#!env ruby

def test subject
	print "  testing #{subject.description}..."
	if subject.test
		puts "\e[32m[OK]\e[0m"
	else
		puts "\e[31m[FAIL]\e[0m"
	end
	subject.result.each_line do |line|
		puts "    #{line}"
	end
end

def class_test klass, test_data
	require "./lib/#{klass.downcase}.rb"
	puts "#{klass} Test"
	test_data.each do |test_datum|
		eval "test #{klass}.new(#{test_datum})"
	end
	puts ""
end
	
	class_test 'Ping', [
		{size: 64,   host: '74.125.235.145', expect: "rtt<100"},
		{size: 1472, host: '74.125.235.145', expect: "rtt<100"},
	]
	class_test 'Ping6', [
		{size: 64,   host: '2404:6800:4004:804::1011', expect: "rtt<100"},
		{size: 1232, host: '2404:6800:4004:804::1011', expect: "rtt<100"},
	]
	class_test 'Dig', [
		{rr: 'A',    proto: 4, domain: 'www.google.com', expect: 'status=="NOERROR" and ans =~ /74.125/'},
		{rr: 'AAAA', proto: 4, domain: 'www.google.com', expect: 'status=="NOERROR" and ans =~ /2404:6800:4004/'},
	]
	class_test 'Tcping', [
		{host: 'www.google.com', proto: 4, port: 80, expect: 'status=="open" and rtt<100'},
		{host: 'www.google.com', proto: 6, port: 80, expect: 'status=="open" and rtt<100'},
	]
